### ISSUE TITLE
Evaluate PR lesson previews via circle

### ISSUE THREAD

**Issue by dpshelio** [HealthBioscienceIDEAS/microscopy-novice#12]
## Definition of done

Evaluate the possibility to build the lesson and display it on circle-ci.
Example: [gh pages for this org](https://github.com/HealthBioscienceIDEAS/healthbioscienceideas.github.io/blob/64867bb7e3ee0121939f8ae32e30f06bcc9a8b74/.circleci/config.yml)

**Comment by milanmlft** [comment]
Alternative to watch out for: [previews may be coming to GitHub Pages](https://github.com/actions/deploy-pages/pull/61) soon as well 👀 
Though currently still in alpha and not available to general public...

**Comment by milanmlft** [comment]
I've looked into using CircleCI, but it might be overkill. Especially because `{sandpaper}` has [its own CI deployment functionality](https://carpentries.github.io/sandpaper/reference/ci_deploy.html) for deploying to GitHub Pages, which we would need to rewrite for CircleCI...

In addition, `{sandpaper}` provides its own form of [PR previews](https://carpentries.github.io/sandpaper/articles/deployment.html#pull-requests) which shows you what has changed in the built markdown files. Although it doesn't provide a preview of the full website, it gives you a nice `diff` view of any changes (which I would say is more useful to review content changes, instead of scrolling through a new version of the website).
I created a mock PR to show what this looks like: #13 

To preview any layout changes to the website, I would suggest just building it locally.
That being said, if the GitHub Pages preview feature ever gets released (see [my previous comment](https://github.com/HealthBioscienceIDEAS/microscopy-novice/issues/12#issuecomment-1803690909)), that could be implemented in a way that fits more nicely with the `{sandpaper}` workflow.

@dpshelio, @K-Meech thoughts?

**Comment by davecash75** [comment]
Hi @milanmlft -
I agree that this will cover the content, which is the main things we will want to check. I guess if we have things that we think might affect the look and feel of the website, like the branding changes, then we might want to build locally to test.
DC

**Comment by MonikaSvata** [comment]
@davecash75 to review if circle is still intended to use.

**Comment by MonikaSvata** [comment]
Closing as circle is not needed.
