### ISSUE TITLE
Day 1 - Episode List with Learning Objectives

### ISSUE THREAD

**Issue by dpshelio** [HealthBioscienceIDEAS/microscopy-novice#8]
## Definition of done

- Topics that will turn into episodes (research questions, design, and measure)
- Obtain feedback from @drmatthews @davecash75 
- Refine objectives

**Comment by K-Meech** [comment]
This is a rough draft of the episode titles and learning objectives for the first day. I've tried to frame learning objectives as 'After following this lesson, learners should be able to…'.  Any suggestions/comments very welcome @drmatthews @davecash75 ! Throughout we will mostly use example data that comes with napari.

## Imaging software

- Explain the pros and cons of different image visualisation tools (e.g. ImageJ, napari and proprietary options)
- Use napari to open images
- Navigate the napari viewer (pan/zoom/swapping between 2D and 3D views…)
- Explain the main parts of the napari user interface

## What is an image?

- Explain how a digital image is made of pixels
- Find the value of different pixels in an image in napari
- Determine an image's dimensions (numpy ndarray .shape)
- Determine an image's data type (numy ndarray .dtype)
- Explain the coordinate system used for images

## Image display

- Create a histogram for an image
- Extract simple summary statistics like min/max/mean pixel value
- Change colormap (LUT) in napari
- Adjust brightness and contrast in napari
- Explain the importance of always retaining a copy of the original pixel values

## Multi-dimensional images

- Explain how axes are handled in napari/numpy (xyz, channels, time)
- Open and navigate images with different dimensions in napari
- Explain what RGB images are and how they are handled in napari
- Split and merge channels in napari

## Filetypes and metadata

- Explain the pros and cons of some popular image filetypes
- Explain the difference between lossless and lossy compression
- Inspect image metadata with the napari-aicsimageio plugin
- Inspect and set an image's scale in napari

**Comment by davecash75** [comment]
Hi @K-Meech - thanks this is a really great start for this day. Please find comments below, hopefully we can discuss at the upcoming meeting.
Are these currently listed in order of how you think they might be presented? On top of the episodes already listed, there is probably a general overview episode of the workshop and how things will work that would come first.
From the comments, I think there might be a broad scale overview of microscopy covering some of the aspects that Nic mentioned in the document only at a high level. I think that would likely come early, either before or after **What is an image**. After these two I think I could then see **filetypes** and **image software**, with the **Image Display** as a more hands-on practical lesson, and finally the multi-dimensional images after that (to get people comfortable with principles in 2D first and then the next group of episodes.
Some of the **Image display** and **Imaging Software** probably could go together (thinking scan/pan/zoom, colormaps, brightness/contrast), and then some of the histogram, stats stuff we do separately, as initially there was talk of including it in the second day. To me the distinction in the episodes is how you navigate around and display the image versus how you measure something from an image.

**Comment by K-Meech** [comment]
Thanks for the comments @davecash75 !

Yes - they are listed in a rough presenting order. I was thinking of introducing napari at the start, so that all the other episodes could have hands-on exercises working with image data in napari. For the basic episodes (what is an image / image display / multi-dimensional images), I was thinking we could use the example data that comes with  napari - progressing from 2D, to 3D, channels + 3D and so on… This is why I originally put the filetypes/metadata at the end, so that we could then use more complex 'real' data with metadata for examples. Plus, by then they should be pretty familiar using napari, so installing additional plugins (like aicsimageio) should be easier.

For your comments:
- Happy to add a general overview episode of the workshop at the start.
- Perhaps the general microscopy overview could be the start of the 'What is an image?' lesson? We could give a very general intro into what a microscope is + how it collects images, leading in to what a pixel really is? Perhaps something similar to the 'a simple microscope' section in [Pete Bankhead's bioimage book](https://bioimagebook.github.io/chapters/1-concepts/1-images_and_pixels/images_and_pixels.html). Otherwise, it can be a separate episode, if we need more detail.
- Happy to move the filetypes/metadata episode earlier, but if we want to immediately have hands-on examples of using that data, it would have to come after a general intro to napari and its user interface
- Yes - happy to merge some of image display / imaging software episodes. I thought it might be useful to have a separate 'Image display' lesson, to make the point that the actual raw pixel values (that you see with a histogram/ summary stats etc) are not modified when you adjust the colormap, brightness or contrast. That the image data (i.e. the raw array) vs how you display it are different concepts. You're right that we can probably cover that in other episodes though or day 2.

**Comment by davecash75** [comment]
HI @K-Meech -
The rationale for napari being first up makes sense and filetypes/metadata later, so we go with skimages to get basic concepts of imaging down and also to formats/metadata being at the end of the day. Some other thoughts:
* At the meeting, I think we also talked about introduing ImageJ a little, less to do a lot of lessons in it and more to make sure they know what tools were out there.
* Agree that microscopy overview could go in front of, or at start of What is an image lesson.
* I think that the split for me between display and measurement/statistics that seems like a natural boundary to me, and whether the latter comes in day 1 or day 2 will depend on how some of our advisors around the course feel.

**Comment by MonikaSvata** [comment]
The list with objectives is done. 
Creating 5 new tickets - 1 for content of each episode.

**Comment by K-Meech** [comment]
I'll close this as there are now drafts of all these episodes merged or as PRs
